apiVersion: v1
kind: Service
metadata:
  name: kube-django-deployment-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8000
    nodePort: 31111
  selector:
    app: kube-django-deployment