apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-django-deployment
  labels:
    app: kube-django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-django-deployment
    template:
      metadata:
        labels:
          app: kube-django-deployment
      spec:
        containers:
        - image: jisunpark/django-sample
          name: django-app
          ports:
          - containerPort: 8000